---
title: "gdpr"
author: "Richard G. Gardiner"
date: "4/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(broom)
library(tidytext)
library(tidylo)

gdpr_violations <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_violations.tsv')
gdpr_text <- readr::read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-21/gdpr_text.tsv')
```

```{r}
gdpr_violations
```

## Plan for Analysis

```{r}
gdpr_violations %>%
  separate_rows(article_violated, sep = "\\|") %>%
  count(article_violated, sort = TRUE) %>%
  mutate(article_violated = fct_reorder(article_violated, n)) %>%
  head(10) %>%
  ggplot(aes(x = article_violated, y = n)) +
  geom_col() +
  labs(x = "Article Violated", y = "Number of Times Citated") +
  coord_flip() +
  theme_minimal() 
```

```{r}
gdpr_violations %>%
  count(name, sort = TRUE)
```

```{r}
gdpr_violations %>%
  group_by(name) %>%
  summarise(sum_price = sum(price, na.rm = TRUE)) %>%
  ungroup() %>%
  arrange(desc(sum_price)) %>%
  head(15) %>%
  mutate(name = fct_reorder(name, sum_price)) %>%
  ggplot(aes(x = name, y = sum_price)) +
  geom_col() +
  labs(x = "Country Name", y = "Total Fines",
       title = "Total Fines by Country Name") +
  scale_y_continuous(labels = scales::dollar_format()) +
  coord_flip()
```


STILL NEED TO WORK ON THIS
```{r}
gdpr_violations %>%
  mutate(date2 = parse_date(date, "%m/%d/%Y")) %>%
  count(date2) %>%
  filter(date2 > "1970-01-01") %>%
  mutate(month = month(date2),
         year = year(date2)) %>%
  group_by(month, year) %>%
  summarise(total = sum(n)) %>%
  ungroup() %>%
  mutate(month_year = as.Date(paste0(year, "-", month, "-01"))) %>%
  ggplot(aes(x = month, y = total, color = factor(year))) +
  geom_line()

gdpr_violations %>%
  mutate(date2 = parse_date(date, "%m/%d/%Y")) %>%
  count(date2) %>%
  filter(date2 > "1970-01-01") %>%
  mutate(month = month(date2),
         year = year(date2)) %>%
  group_by(month, year) %>%
  summarise(total = sum(n)) %>%
  ungroup() %>%
  mutate(month_year = as.Date(paste0(year, "-", month, "-01"))) %>%
  ggplot(aes(x = month_year, y = total)) +
  geom_line() +
  theme_minimal() +
  labs(x = "", y = "Number of Fines Issued",
       title = "Number of Fines Issued by Month")
```

```{r}
gdpr_violations %>%
  mutate(date2 = parse_date(date, "%m/%d/%Y")) %>%
  filter(date2 > "1970-01-01") %>%
  mutate(year = year(date2)) %>%
  group_by(year) %>%
  summarise(total = sum(price)) %>%
  ungroup()  %>%
  ggplot(aes(x = year, y = total)) +
  geom_col() +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(x = "Year",
       y = "Total Fines (in Euros)",
       title = "Total Number of Fines for Each Year",
       subtitle = "GDPR took effect May 28, 2018. Data reported through April 2020.") +
  theme_minimal()
```

```{r}
# Google had HUGE fine
gdpr_violations %>%
  mutate(scaled_price = scale(price)) %>%
  arrange(desc(price))

gdpr_violations %>%
  ggplot(aes(x = price)) +
  geom_histogram() +
  scale_x_log10(labels = scales::dollar_format()) 
```

```{r}
gdpr_violations %>%
  group_by(controller) %>%
  summarise(total_fines = sum(price)) %>%
  ungroup() %>%
  mutate(controller = fct_reorder(controller, total_fines)) %>%
  arrange(desc(total_fines)) %>%
  head(20) %>%
  ggplot(aes(x = controller, y = total_fines)) +
  geom_col() +
  scale_y_continuous(labels = scales::dollar_format()) +
  labs(x = "Entity Fined", y = "Total Fines") +
  coord_flip() +
  theme_minimal()
```

```{r}
gdpr_violations %>%
  mutate(country = fct_lump(name, 5),
         article_violated = fct_lump(article_violated, 5),
         type = fct_lump(type, 5)) %>%
  lm(log10(price + 0.1) ~ country + article_violated + type, data = .) %>%
  tidy() %>%
  mutate(lower = estimate - std.error * 1.96,
         upper = estimate + std.error * 1.96,
         term = fct_reorder(term, estimate),
         significant = ifelse(p.value < 0.05, 1, 0)) %>% 
  ggplot(aes(x = term, y = estimate, color = as.factor(significant))) +
  geom_point(show.legend = FALSE) +
  geom_errorbar(aes(ymin = lower, ymax = upper), show.legend = FALSE) +
  geom_hline(yintercept = 0, lty = 2) +
  labs(title = "Predictors of the Price of a Fine",
       subtitle = "Blue color indicates statistical significance",
       x = "",
       y = "Coefficient Estimate") +
  coord_flip() +
  theme_minimal()
  
```

```{r}
log_odds_chapter <- gdpr_text %>%
  unnest_tokens(word, gdpr_text) %>%
  count(chapter, word) %>%
  bind_log_odds(set = chapter, feature = word, n = n)

log_odds_chapter %>%
  arrange(-log_odds)

# Looking at a single Chapter
log_odds_chapter %>%
  group_by(chapter) %>%
  top_n(10, log_odds) %>%
  ungroup() %>%
  mutate(chapter = as.factor(chapter),
         word = reorder_within(word, log_odds, chapter)) %>%
  ggplot(aes(x = word, y = log_odds, fill = chapter)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~chapter, scales = "free") +
  scale_x_reordered() +
  labs(x = "",
       y = "Log-Odds Ratio",
       title = "Most Unique Words by each Chapter") +
  coord_flip() 
```

6. Map of country and fines
