---
title: "measles"
author: "Richard G. Gardiner"
date: "5/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lme4)

measles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-25/measles.csv')
```

```{r}
measles %>%
  distinct(state)
```


```{r}
measles %>%
  group_by(state) %>%
  summarise(average_vaccination = mean(mmr, na.rm = TRUE),
            sd = sd(mmr, na.rm = TRUE),
            lower = average_vaccination - sd,
            upper = average_vaccination + sd) %>%
  filter(average_vaccination > 0) %>% # some states have -1 as the rate.. Doesn't make any sense.
  mutate(state = fct_reorder(state, average_vaccination)) %>%
  ggplot(aes(x = state, y = average_vaccination)) +
  geom_point() +
  geom_errorbar(aes(ymin = lower, ymax = upper)) +
  labs(x = "", y = "Vaccination Rates", 
       title = "Average Vaccination Rates for Schools",
       caption = "Error Bars Indicate One Standard Deviation Above/Below") +
  coord_flip() +
  theme_minimal() 
```

```{r}
measles %>%
  count(xrel)

measles %>%
  filter(!is.na(xrel)) %>%
  group_by(state) %>%
  count(xrel)

measles %>%
  ggplot(aes(xmed)) +
  geom_histogram()

measles %>%
  ggplot(aes(xper)) +
  geom_histogram()
```

The exemptions are supposed to be percentages, but xper has a value over 100%
```{r}
summary(measles) 
```


```{r}
# plotting Idaho with Washington as second choice
measles %>%
  filter(overall != -1) %>%
  group_by(state) %>%
  summarise(std = sd(overall, na.rm = TRUE)) %>%
  arrange(-std)

idaho <- map_data("state") %>%
  filter(region == "idaho")

washington <- map_data("state") %>%
  filter(region == "washington")

measles %>%
  filter(state == "Idaho") %>%
  ggplot() +
  geom_polygon(data = idaho, aes(x = long, y = lat, group = group)) +
  geom_point(aes(x = lng, y = lat, color = overall)) +
  theme_void() +
  xlim(-120, -110) +
  scale_color_gradient2(low = "red2", mid = 50, high = "blue")


measles %>%
  filter(state == "Washington") %>%
  ggplot() +
  geom_polygon(data = washington, aes(x = long, y = lat, group = group)) +
  geom_point(aes(x = lng, y = lat, color = overall)) +
  theme_void() +
  scale_color_gradient2(low = "red2", midpoint = 50, high = "blue", mid = "white")
```

```{r}
measles %>%
  filter(mmr > 0,
         !is.na(type)) %>%
  group_by(type) %>%
  summarise(average_vacc = mean(mmr)) %>%
  ungroup %>%
  arrange(-average_vacc)
```

## Analyses

```{r}
measles %>%
  filter(mmr > 0) %>%
  select(mmr, type, state) %>%
  mutate(type = fct_relevel(type, "Public")) %>%
  lmer(mmr ~ type + (1 | state), data = .) %>%
  broom::tidy(conf.int = TRUE) %>%
  filter(str_detect(term, "type")) %>%
  mutate(term = str_remove(term, "type"),
         term = fct_reorder(term, estimate),
         sig = ifelse(estimate < 0 & conf.high < 0, "negative",
                      ifelse(estimate > 0 & conf.low > 0, "positive", "not significant"))) %>%
  ggplot(aes(x = term, y = estimate, color = sig)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  coord_flip() +
  geom_hline(yintercept = 0, lty = 2, color = "red") +
  theme_minimal() +
  scale_color_manual(values = c("red", "black")) +
  labs(x = "", y = "Coefficient Estimates", color = "Statistical Significance",
       title = "Do different types of schools have different MMR vaccination rates?",
       subtitle = "Charter and private schools are much lower than public schools",
       caption = "Significance at the 95% level.\nPublic Schools serve as baseline group")
```
