---
title: "passwords"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(tidyverse)

passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Is Your Password Popular?

```{r}
passwords %>%
  select(rank, password, strength, offline_crack_sec) %>%
  filter(!is.na(password)) %>%
  datatable(colnames = c("Rank", "Password", "Password Strength",
                         "Seconds to Crack"),
            rownames = FALSE,
            options = list(pageLength = 15))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Password Strength by Category

```{r}
passwords %>%
  group_by(category) %>%
  summarise(avg_strength = mean(strength, na.rm = TRUE),
            std_strength = sd(strength, na.rm = TRUE),
            sd_lower = avg_strength - std_strength,
            sd_upper = avg_strength + std_strength) %>%
  ungroup() %>%
  mutate(category = fct_reorder(str_to_title(category), avg_strength)) %>%
  filter(!is.na(category)) %>%
  ggplot(aes(x = category, y = avg_strength,
             ymin = sd_lower, ymax = sd_upper)) +
  geom_point() +
  geom_errorbar() +
  coord_flip() +
  theme_minimal() +
  labs(x = "Password Category", y = "Average Password Strength",
       title = "Average Password Strength by Category",
       subtitle = "Error Bars are 1 Standard Deviation Above/Below the Mean")
```

### The Importance of Including Letters and Numbers

```{r}
passwords %>%
  mutate(length = nchar(password),
         alpha_numeric = factor(ifelse(str_detect(password, "[:alpha:][:digit:]|[:digit:][:alpha:]"),
                                1, 0))) %>%
  select(password, length, strength, alpha_numeric) %>%
  group_by(alpha_numeric) %>%
  add_count(alpha_numeric) %>%
  summarise(avg_strength = mean(strength, na.rm = TRUE),
            median_strength = median(strength, na.rm = TRUE),
            standard_dev = sd(strength, na.rm = TRUE)) %>%
  ungroup() %>%
  filter(!is.na(alpha_numeric)) %>%
  mutate(sd_lower = avg_strength - standard_dev,
         sd_upper = avg_strength + standard_dev) %>%
  ggplot(aes(x = alpha_numeric, y = avg_strength,
             ymin = sd_lower, ymax = sd_upper)) +
  geom_point() +
  geom_errorbar(width = 0.4) +
  theme_minimal() +
  labs(x = "Password Includes Numbers and Letters",
       y = "Average Strength",
       title = "Passwords with Letters and Numbers are MUCH Stronger") +
  scale_x_discrete(labels = c("No", "Yes")) +
  scale_y_continuous(limits = c(0, 45))
```

