---
title: "volcanos"
author: "Richard G. Gardiner"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(lubridate)

volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')

```

```{r}
world <- map_data(map = "world")

world %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano, aes(x = longitude, y = latitude), color = "red") +
  theme_void()

world %>%
  filter(region == "USA",
         !subregion %in% c("Hawaii", "Alaska")) %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano %>%
               filter(country == "United States",
                      !str_detect(region, "Hawaii|Alas|Marianas"),
                      latitude > 0), aes(x = longitude, y = latitude), color = "red") +
  theme_void()

world %>%
  filter(region == "Philippines") %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano %>%
               filter(country == "Philippines"), aes(x = longitude, y = latitude), color = "red") +
  # expand_limits(y = c(0, 60), x = c(110, 140)) 
  coord_map() +
  theme_void()
```


```{r}
volcano_eruption_location <- eruptions %>%
  filter(!is.na(vei)) %>%
  select(volcano_number, volcano_name, vei) %>%
  left_join(volcano, by = "volcano_number")

world %>%
  filter(region == "USA",
         !subregion %in% c("Hawaii", "Alaska")) %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano_eruption_location %>%
               filter(country == "United States",
                      !str_detect(region, "Hawaii|Alas|Marianas"),
                      latitude > 0), aes(x = longitude, y = latitude, size = vei), 
             color = "red",
             show.legend = FALSE) +
  theme_void() +
  labs(title = "Selected Volcanic Eruptions in US",
       subtitle = "Size = Scale of Eruption")

world %>%
  filter(region == "Philippines") %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano_eruption_location %>%
               filter(country == "Philippines"), aes(x = longitude, y = latitude, size = vei),
             color = "red",
             show.legend = FALSE) +
  coord_map() +
  theme_void() +
  labs(title = "Selected Volcanic Eruptions in the Philippines",
       subtitle = "Size = Scale of Eruption")
```


```{r}
eruptions %>%
  filter(!is.na(vei)) %>%
  count(vei) %>%
  ggplot(aes(x = vei, y = n)) +
  geom_col()

volcano_eruption_location %>%
  filter(!is.na(primary_volcano_type)) %>%
  mutate(primary_volcano_type = str_remove(primary_volcano_type, "\\(es\\)|\\(s\\)")) %>%
  group_by(primary_volcano_type) %>%
  mutate(mean = mean(vei)) %>%
  ungroup()  %>%
  mutate(primary_volcano_type = fct_reorder(primary_volcano_type, mean)) %>%
  ggplot(aes(x = primary_volcano_type, y = vei)) +
  geom_boxplot() +
  coord_flip()
```

```{r}
world %>%
  ggplot() +
  geom_polygon(aes(x = long, y = lat, group = group)) +
  geom_point(data = volcano_eruption_location %>%
               filter(vei == 7), 
             aes(x = longitude, y = latitude), color = "red", size = 3) +
  theme_void() +
  labs(title = "Location of the Largest Eruptions")
```


```{r}
eruptions %>%
  filter(!is.na(end_year),
         !is.na(start_year),
         !is.na(vei),
         vei < 7) %>%
  mutate(start_month = ifelse(start_month == 0, 1, start_month),
         start_day = ifelse(start_day == 0, 1, start_day),
         start_date = mdy(paste0(start_month,"/",start_day,"/",start_year)),
         end_date = mdy(paste0(end_month,"/",end_day,"/",end_year)),
         number_days = end_date - start_date) %>%
  arrange(-vei) %>%
  group_by(vei) %>%
  summarise(mean_days = mean(number_days, na.rm = TRUE),
            sd_days = sd(number_days, na.rm = TRUE),
            count = n()) %>%
  ggplot(aes(x = vei, y = mean_days)) +
  geom_col()

```


## Analyses

3. Events: Look at "event remarks"